// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Model
{
    public partial class Emprestimo1
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string Livro { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Cliente { get; set; }
        [Column("dataemprestimo", TypeName = "datetime")]
        public DateTime? Dataemprestimo { get; set; }
        [Column("datadevolucao", TypeName = "datetime")]
        public DateTime? Datadevolucao { get; set; }
    }
}