// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Model
{
    [Table("tb_Livro")]
    public partial class TbLivro
    {
        public TbLivro()
        {
            TbRelacional = new HashSet<TbRelacional>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(14)]
        [Unicode(false)]
        public string Titulo { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Autor { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Editora { get; set; }
        public bool Emprestimo { get; set; }
        [Unicode(false)]
        public string Imagem { get; set; }

        [InverseProperty("IdLivroNavigation")]
        public virtual ICollection<TbRelacional> TbRelacional { get; set; }
    }
}