// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Model
{
    [Table("tb_Mapa")]
    public partial class TbMapa
    {
        public TbMapa()
        {
            TbRelacional = new HashSet<TbRelacional>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Dataa { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Locall { get; set; }
        [Unicode(false)]
        public string Imagem { get; set; }

        [InverseProperty("IdMapaNavigation")]
        public virtual ICollection<TbRelacional> TbRelacional { get; set; }
    }
}