// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Library.Model
{
    [Table("tb_Relacional")]
    public partial class TbRelacional
    {
        [Key]
        public int Id { get; set; }
        [Column("Id_Cliente")]
        public int? IdCliente { get; set; }
        [Column("Id_Livro")]
        public int? IdLivro { get; set; }
        [Column("Id_Mapa")]
        public int? IdMapa { get; set; }
        [Column("Id_Pesquisa")]
        public int? IdPesquisa { get; set; }
        [Column("Id_Emprestimo")]
        public int? IdEmprestimo { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("TbRelacional")]
        public virtual TbCliente IdClienteNavigation { get; set; }
        [ForeignKey("IdEmprestimo")]
        [InverseProperty("TbRelacional")]
        public virtual TbEmprestimo IdEmprestimoNavigation { get; set; }
        [ForeignKey("IdLivro")]
        [InverseProperty("TbRelacional")]
        public virtual TbLivro IdLivroNavigation { get; set; }
        [ForeignKey("IdMapa")]
        [InverseProperty("TbRelacional")]
        public virtual TbMapa IdMapaNavigation { get; set; }
        [ForeignKey("IdPesquisa")]
        [InverseProperty("TbRelacional")]
        public virtual TbPesquisa IdPesquisaNavigation { get; set; }
    }
}